// Interfaces/IOpenAiSqlGenerator.cs
using System.Threading.Tasks;

namespace SemanticSearchApi.Interfaces
{
    /// <summary>
    /// Defines a contract for generating SQL queries from natural language using OpenAI.
    /// </summary>
    public interface IOpenAiSqlGenerator
    {
        /// <summary>
        /// Generates a SQL query string based on the user's raw natural language input.
        /// </summary>
        /// <param name="naturalLanguageQuery">The raw user query in natural language.</param>
        /// <returns>A SQL query string generated by OpenAI.</returns>
        Task<string> GenerateSqlAsync(string naturalLanguageQuery);
    }
}
